#!/bin/bash

# Sort out file permissions
if [[ $(id dalmatiner 2>/dev/null) ]] ;then
    chown -R dalmatiner:dalmatiner /var/lib/dfe
    chown -R dalmatiner:dalmatiner /var/log/dfe
fi

CONFFILE=/etc/dfe/dalmatinerfe.conf

if [ ! -f "${CONFFILE}" ]
then
    echo "Creating new configuration from example file."
    cp ${CONFFILE}.example ${CONFFILE}
    sed -i -e "s/dqe_idx_ddb/dqe_idx_pg/g" ${CONFFILE}
else
    echo "Please update your configuration according to the update manual!"
fi
